-S:0: open -S: no such file or directory
os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $-2
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $1
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $1
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	PCDATA	$0, $0
	0x0008 00008 (<autogenerated>:1)	PCDATA	$1, $0
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	XORPS	X0, X0
	0x0010 00016 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0015 00021 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
	0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
	rel 22+4 t=8 os.(*file).close+0
"".reverse STEXT nosplit size=95 args=0x18 locals=0x18
	0x0000 00000 (reverse.go:5)	TEXT	"".reverse(SB), NOSPLIT|ABIInternal, $24-24
	0x0000 00000 (reverse.go:5)	SUBQ	$24, SP
	0x0004 00004 (reverse.go:5)	MOVQ	BP, 16(SP)
	0x0009 00009 (reverse.go:5)	LEAQ	16(SP), BP
	0x000e 00014 (reverse.go:5)	PCDATA	$0, $-2
	0x000e 00014 (reverse.go:5)	PCDATA	$1, $-2
	0x000e 00014 (reverse.go:5)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x000e 00014 (reverse.go:5)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x000e 00014 (reverse.go:5)	FUNCDATA	$2, gclocals·d571c0f6cf0af59df28f76498f639cf2(SB)
	0x000e 00014 (reverse.go:7)	PCDATA	$0, $0
	0x000e 00014 (reverse.go:7)	PCDATA	$1, $0
	0x000e 00014 (reverse.go:7)	MOVQ	"".s+40(SP), CX
	0x0013 00019 (reverse.go:7)	LEAQ	-1(CX), DX
	0x0017 00023 (reverse.go:7)	PCDATA	$0, $1
	0x0017 00023 (reverse.go:7)	PCDATA	$1, $1
	0x0017 00023 (reverse.go:7)	MOVQ	"".s+32(SP), BX
	0x001c 00028 (reverse.go:7)	XORL	AX, AX
	0x001e 00030 (reverse.go:7)	JMP	50
	0x0020 00032 (reverse.go:8)	MOVQ	(BX)(DX*8), DI
	0x0024 00036 (reverse.go:8)	MOVQ	DI, (BX)(AX*8)
	0x0028 00040 (reverse.go:8)	MOVQ	SI, (BX)(DX*8)
	0x002c 00044 (reverse.go:7)	INCQ	AX
	0x002f 00047 (reverse.go:7)	DECQ	DX
	0x0032 00050 (reverse.go:7)	CMPQ	AX, DX
	0x0035 00053 (reverse.go:7)	JGE	71
	0x0037 00055 (reverse.go:8)	CMPQ	AX, CX
	0x003a 00058 (reverse.go:8)	JCC	89
	0x003c 00060 (reverse.go:8)	MOVQ	(BX)(AX*8), SI
	0x0040 00064 (reverse.go:8)	CMPQ	DX, CX
	0x0043 00067 (reverse.go:8)	JCS	32
	0x0045 00069 (reverse.go:8)	JMP	81
	0x0047 00071 (reverse.go:7)	PCDATA	$0, $-1
	0x0047 00071 (reverse.go:7)	PCDATA	$1, $-1
	0x0047 00071 (reverse.go:7)	MOVQ	16(SP), BP
	0x004c 00076 (reverse.go:7)	ADDQ	$24, SP
	0x0050 00080 (reverse.go:7)	RET
	0x0051 00081 (reverse.go:8)	PCDATA	$0, $0
	0x0051 00081 (reverse.go:8)	PCDATA	$1, $1
	0x0051 00081 (reverse.go:8)	MOVQ	DX, AX
	0x0054 00084 (reverse.go:8)	CALL	runtime.panicIndex(SB)
	0x0059 00089 (reverse.go:8)	CALL	runtime.panicIndex(SB)
	0x005e 00094 (reverse.go:8)	XCHGL	AX, AX
	0x0000 48 83 ec 18 48 89 6c 24 10 48 8d 6c 24 10 48 8b  H...H.l$.H.l$.H.
	0x0010 4c 24 28 48 8d 51 ff 48 8b 5c 24 20 31 c0 eb 12  L$(H.Q.H.\$ 1...
	0x0020 48 8b 3c d3 48 89 3c c3 48 89 34 d3 48 ff c0 48  H.<.H.<.H.4.H..H
	0x0030 ff ca 48 39 d0 7d 10 48 39 c8 73 1d 48 8b 34 c3  ..H9.}.H9.s.H.4.
	0x0040 48 39 ca 72 db eb 0a 48 8b 6c 24 10 48 83 c4 18  H9.r...H.l$.H...
	0x0050 c3 48 89 d0 e8 00 00 00 00 e8 00 00 00 00 90     .H.............
	rel 85+4 t=8 runtime.panicIndex+0
	rel 90+4 t=8 runtime.panicIndex+0
"".main STEXT size=299 args=0x0 locals=0xb8
	0x0000 00000 (reverse.go:13)	TEXT	"".main(SB), ABIInternal, $184-0
	0x0000 00000 (reverse.go:13)	MOVQ	(TLS), CX
	0x0009 00009 (reverse.go:13)	LEAQ	-56(SP), AX
	0x000e 00014 (reverse.go:13)	CMPQ	AX, 16(CX)
	0x0012 00018 (reverse.go:13)	PCDATA	$0, $-2
	0x0012 00018 (reverse.go:13)	JLS	289
	0x0018 00024 (reverse.go:13)	PCDATA	$0, $-1
	0x0018 00024 (reverse.go:13)	SUBQ	$184, SP
	0x001f 00031 (reverse.go:13)	MOVQ	BP, 176(SP)
	0x0027 00039 (reverse.go:13)	LEAQ	176(SP), BP
	0x002f 00047 (reverse.go:13)	PCDATA	$0, $-2
	0x002f 00047 (reverse.go:13)	PCDATA	$1, $-2
	0x002f 00047 (reverse.go:13)	FUNCDATA	$0, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x002f 00047 (reverse.go:13)	FUNCDATA	$1, gclocals·568470801006e5c0dc3947ea998fe279(SB)
	0x002f 00047 (reverse.go:13)	FUNCDATA	$2, gclocals·ba192201ac73f95fb90b551d9176d705(SB)
	0x002f 00047 (reverse.go:13)	FUNCDATA	$3, "".main.stkobj(SB)
	0x002f 00047 (reverse.go:14)	PCDATA	$0, $0
	0x002f 00047 (reverse.go:14)	PCDATA	$1, $0
	0x002f 00047 (reverse.go:14)	MOVUPS	""..stmp_0(SB), X0
	0x0036 00054 (reverse.go:14)	MOVUPS	X0, "".a+64(SP)
	0x003b 00059 (reverse.go:14)	MOVUPS	""..stmp_0+16(SB), X0
	0x0042 00066 (reverse.go:14)	MOVUPS	X0, "".a+80(SP)
	0x0047 00071 (reverse.go:14)	MOVUPS	""..stmp_0+32(SB), X0
	0x004e 00078 (reverse.go:14)	MOVUPS	X0, "".a+96(SP)
	0x0053 00083 (reverse.go:16)	PCDATA	$0, $1
	0x0053 00083 (reverse.go:16)	LEAQ	"".a+64(SP), AX
	0x0058 00088 (reverse.go:16)	PCDATA	$0, $0
	0x0058 00088 (reverse.go:16)	MOVQ	AX, (SP)
	0x005c 00092 (reverse.go:16)	MOVQ	$6, 8(SP)
	0x0065 00101 (reverse.go:16)	MOVQ	$6, 16(SP)
	0x006e 00110 (reverse.go:16)	CALL	"".reverse(SB)
	0x0073 00115 (reverse.go:18)	MOVUPS	"".a+64(SP), X0
	0x0078 00120 (reverse.go:18)	MOVUPS	X0, ""..autotmp_8+112(SP)
	0x007d 00125 (reverse.go:18)	MOVUPS	"".a+80(SP), X0
	0x0082 00130 (reverse.go:18)	MOVUPS	X0, ""..autotmp_8+128(SP)
	0x008a 00138 (reverse.go:18)	MOVUPS	"".a+96(SP), X0
	0x008f 00143 (reverse.go:18)	MOVUPS	X0, ""..autotmp_8+144(SP)
	0x0097 00151 (reverse.go:18)	PCDATA	$0, $1
	0x0097 00151 (reverse.go:18)	LEAQ	type.[6]int(SB), AX
	0x009e 00158 (reverse.go:18)	PCDATA	$0, $0
	0x009e 00158 (reverse.go:18)	MOVQ	AX, (SP)
	0x00a2 00162 (reverse.go:18)	PCDATA	$0, $1
	0x00a2 00162 (reverse.go:18)	LEAQ	""..autotmp_8+112(SP), AX
	0x00a7 00167 (reverse.go:18)	PCDATA	$0, $0
	0x00a7 00167 (reverse.go:18)	MOVQ	AX, 8(SP)
	0x00ac 00172 (reverse.go:18)	CALL	runtime.convT2Enoptr(SB)
	0x00b1 00177 (reverse.go:18)	MOVQ	16(SP), AX
	0x00b6 00182 (reverse.go:18)	PCDATA	$0, $2
	0x00b6 00182 (reverse.go:18)	MOVQ	24(SP), CX
	0x00bb 00187 (reverse.go:18)	PCDATA	$1, $1
	0x00bb 00187 (reverse.go:18)	XORPS	X0, X0
	0x00be 00190 (reverse.go:18)	MOVUPS	X0, ""..autotmp_14+160(SP)
	0x00c6 00198 (reverse.go:18)	MOVQ	AX, ""..autotmp_14+160(SP)
	0x00ce 00206 (reverse.go:18)	PCDATA	$0, $0
	0x00ce 00206 (reverse.go:18)	MOVQ	CX, ""..autotmp_14+168(SP)
	0x00d6 00214 (<unknown line number>)	NOP
	0x00d6 00214 ($GOROOT/src/fmt/print.go:242)	PCDATA	$0, $1
	0x00d6 00214 ($GOROOT/src/fmt/print.go:242)	MOVQ	os.Stdout(SB), AX
	0x00dd 00221 ($GOROOT/src/fmt/print.go:242)	PCDATA	$0, $3
	0x00dd 00221 ($GOROOT/src/fmt/print.go:242)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x00e4 00228 ($GOROOT/src/fmt/print.go:242)	PCDATA	$0, $1
	0x00e4 00228 ($GOROOT/src/fmt/print.go:242)	MOVQ	CX, (SP)
	0x00e8 00232 ($GOROOT/src/fmt/print.go:242)	PCDATA	$0, $0
	0x00e8 00232 ($GOROOT/src/fmt/print.go:242)	MOVQ	AX, 8(SP)
	0x00ed 00237 ($GOROOT/src/fmt/print.go:242)	PCDATA	$0, $1
	0x00ed 00237 ($GOROOT/src/fmt/print.go:242)	PCDATA	$1, $0
	0x00ed 00237 ($GOROOT/src/fmt/print.go:242)	LEAQ	""..autotmp_14+160(SP), AX
	0x00f5 00245 ($GOROOT/src/fmt/print.go:242)	PCDATA	$0, $0
	0x00f5 00245 ($GOROOT/src/fmt/print.go:242)	MOVQ	AX, 16(SP)
	0x00fa 00250 ($GOROOT/src/fmt/print.go:242)	MOVQ	$1, 24(SP)
	0x0103 00259 ($GOROOT/src/fmt/print.go:242)	MOVQ	$1, 32(SP)
	0x010c 00268 ($GOROOT/src/fmt/print.go:242)	CALL	fmt.Fprint(SB)
	0x0111 00273 (reverse.go:18)	MOVQ	176(SP), BP
	0x0119 00281 (reverse.go:18)	ADDQ	$184, SP
	0x0120 00288 (reverse.go:18)	RET
	0x0121 00289 (reverse.go:18)	NOP
	0x0121 00289 (reverse.go:13)	PCDATA	$1, $-1
	0x0121 00289 (reverse.go:13)	PCDATA	$0, $-2
	0x0121 00289 (reverse.go:13)	CALL	runtime.morestack_noctxt(SB)
	0x0126 00294 (reverse.go:13)	PCDATA	$0, $-1
	0x0126 00294 (reverse.go:13)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 8d 44 24 c8 48 3b  eH..%....H.D$.H;
	0x0010 41 10 0f 86 09 01 00 00 48 81 ec b8 00 00 00 48  A.......H......H
	0x0020 89 ac 24 b0 00 00 00 48 8d ac 24 b0 00 00 00 0f  ..$....H..$.....
	0x0030 10 05 00 00 00 00 0f 11 44 24 40 0f 10 05 00 00  ........D$@.....
	0x0040 00 00 0f 11 44 24 50 0f 10 05 00 00 00 00 0f 11  ....D$P.........
	0x0050 44 24 60 48 8d 44 24 40 48 89 04 24 48 c7 44 24  D$`H.D$@H..$H.D$
	0x0060 08 06 00 00 00 48 c7 44 24 10 06 00 00 00 e8 00  .....H.D$.......
	0x0070 00 00 00 0f 10 44 24 40 0f 11 44 24 70 0f 10 44  .....D$@..D$p..D
	0x0080 24 50 0f 11 84 24 80 00 00 00 0f 10 44 24 60 0f  $P...$......D$`.
	0x0090 11 84 24 90 00 00 00 48 8d 05 00 00 00 00 48 89  ..$....H......H.
	0x00a0 04 24 48 8d 44 24 70 48 89 44 24 08 e8 00 00 00  .$H.D$pH.D$.....
	0x00b0 00 48 8b 44 24 10 48 8b 4c 24 18 0f 57 c0 0f 11  .H.D$.H.L$..W...
	0x00c0 84 24 a0 00 00 00 48 89 84 24 a0 00 00 00 48 89  .$....H..$....H.
	0x00d0 8c 24 a8 00 00 00 48 8b 05 00 00 00 00 48 8d 0d  .$....H......H..
	0x00e0 00 00 00 00 48 89 0c 24 48 89 44 24 08 48 8d 84  ....H..$H.D$.H..
	0x00f0 24 a0 00 00 00 48 89 44 24 10 48 c7 44 24 18 01  $....H.D$.H.D$..
	0x0100 00 00 00 48 c7 44 24 20 01 00 00 00 e8 00 00 00  ...H.D$ ........
	0x0110 00 48 8b ac 24 b0 00 00 00 48 81 c4 b8 00 00 00  .H..$....H......
	0x0120 c3 e8 00 00 00 00 e9 d5 fe ff ff                 ...........
	rel 5+4 t=17 TLS+0
	rel 50+4 t=16 ""..stmp_0+0
	rel 62+4 t=16 ""..stmp_0+16
	rel 74+4 t=16 ""..stmp_0+32
	rel 111+4 t=8 "".reverse+0
	rel 154+4 t=16 type.[6]int+0
	rel 173+4 t=8 runtime.convT2Enoptr+0
	rel 217+4 t=16 os.Stdout+0
	rel 224+4 t=16 go.itab.*os.File,io.Writer+0
	rel 269+4 t=8 fmt.Fprint+0
	rel 290+4 t=8 runtime.morestack_noctxt+0
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info.fmt.Print$abstract SDWARFINFO dupok size=40
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 00 01 01 11 61 00  .fmt.Print....a.
	0x0010 00 00 00 00 00 11 6e 00 01 00 00 00 00 11 65 72  ......n.......er
	0x0020 72 00 01 00 00 00 00 00                          r.......
	rel 0+0 t=24 type.[]interface {}+0
	rel 0+0 t=24 type.error+0
	rel 0+0 t=24 type.int+0
	rel 17+4 t=29 go.info.[]interface {}+0
	rel 25+4 t=29 go.info.int+0
	rel 35+4 t=29 go.info.error+0
go.loc.os.(*File).close SDWARFLOC dupok size=0
go.info.os.(*File).close SDWARFINFO dupok size=55
	0x0000 03 6f 73 2e 28 2a 46 69 6c 65 29 2e 63 6c 6f 73  .os.(*File).clos
	0x0010 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  e...............
	0x0020 00 00 01 9c 00 00 00 00 01 0f 7e 72 30 00 01 f0  ..........~r0...
	0x0030 01 00 00 00 00 00 00                             .......
	rel 0+0 t=24 type.*os.File+0
	rel 0+0 t=24 type.error+0
	rel 18+8 t=1 os.(*File).close+0
	rel 26+8 t=1 os.(*File).close+26
	rel 36+4 t=30 gofile..<autogenerated>+0
	rel 49+4 t=29 go.info.error+0
go.range.os.(*File).close SDWARFRANGE dupok size=0
go.debuglines.os.(*File).close SDWARFMISC dupok size=12
	0x0000 04 01 0f 06 41 06 af 04 01 03 00 01              ....A.......
go.loc."".reverse SDWARFLOC size=111
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 07 00 9c 93 08 91 08 93 08 00 00 00 00 00 00 00  ................
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 01 00 50 00 00 00 00  ...........P....
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 00 00 00 00 00 00 00 00 01 00 51 00  ..............Q.
	0x0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ...............
	rel 0+8 t=53 "".reverse+0
	rel 8+8 t=53 "".reverse+95
	rel 41+8 t=53 "".reverse+47
	rel 49+8 t=53 "".reverse+84
	rel 76+8 t=53 "".reverse+23
	rel 84+8 t=53 "".reverse+95
go.info."".reverse SDWARFINFO size=91
	0x0000 03 22 22 2e 72 65 76 65 72 73 65 00 00 00 00 00  ."".reverse.....
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 01 9c 00 00  ................
	0x0020 00 00 01 10 73 00 00 05 00 00 00 00 00 00 00 00  ....s...........
	0x0030 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 0b 69 00 07 00 00 00 00 00 00 00 00 0b 6a 00  ..i...........j.
	0x0050 07 00 00 00 00 00 00 00 00 00 00                 ...........
	rel 0+0 t=24 type.[]int+0
	rel 12+8 t=1 "".reverse+0
	rel 20+8 t=1 "".reverse+95
	rel 30+4 t=30 gofile../Users/renfakai/go/src/GoStudy/ch04/reverse.go+0
	rel 40+4 t=29 go.info.[]int+0
	rel 44+4 t=29 go.loc."".reverse+0
	rel 49+8 t=1 "".reverse+14
	rel 57+8 t=1 "".reverse+95
	rel 69+4 t=29 go.info.int+0
	rel 73+4 t=29 go.loc."".reverse+41
	rel 81+4 t=29 go.info.int+0
	rel 85+4 t=29 go.loc."".reverse+76
go.range."".reverse SDWARFRANGE size=0
go.debuglines."".reverse SDWARFMISC size=34
	0x0000 04 02 0a 13 9d 06 41 06 92 06 37 06 5e 06 2d 06  ......A...7.^.-.
	0x0010 2d 06 2d 06 24 06 2d 06 90 06 74 06 91 04 01 03  -.-.$.-...t.....
	0x0020 79 01                                            y.
go.loc."".main SDWARFLOC size=37
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 03 00 91 80 7f 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0020 00 00 00 00 00                                   .....
	rel 0+8 t=53 "".main+54
	rel 8+8 t=53 "".main+299
go.info."".main SDWARFINFO size=81
	0x0000 03 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 0b 61 00 0e 00 00 00 00 00 00 00 00 06 00 00 00  .a..............
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 12 00 00 00 12 00 00 00 00 00 00  ................
	0x0050 00                                               .
	rel 0+0 t=24 type.[1]interface {}+0
	rel 0+0 t=24 type.[6]int+0
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+299
	rel 27+4 t=30 gofile../Users/renfakai/go/src/GoStudy/ch04/reverse.go+0
	rel 36+4 t=29 go.info.[6]int+0
	rel 40+4 t=29 go.loc."".main+0
	rel 45+4 t=29 go.info.fmt.Print$abstract+0
	rel 49+8 t=1 "".main+214
	rel 57+8 t=1 "".main+273
	rel 65+4 t=30 gofile../Users/renfakai/go/src/GoStudy/ch04/reverse.go+0
	rel 74+4 t=29 go.info.fmt.Print$abstract+13
go.range."".main SDWARFRANGE size=0
go.debuglines."".main SDWARFMISC size=48
	0x0000 04 02 03 07 14 0a ff f6 06 55 06 08 43 06 41 06  .........U..C.A.
	0x0010 08 2f 06 41 04 03 06 02 47 03 db 01 fa 06 55 04  ./.A....G.....U.
	0x0020 02 06 02 1c 03 a4 7e fb 03 7f ab 04 01 03 74 01  ......~.......t.
runtime.nilinterequal·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.nilinterequal+0
runtime.memequal64·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.memequal64+0
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 08 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 08 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
""..inittask SNOPTRDATA size=32
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
""..stmp_0 SRODATA size=48
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 02 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00  ................
	0x0020 04 00 00 00 00 00 00 00 05 00 00 00 00 00 00 00  ................
type..namedata.*[]int- SRODATA dupok size=9
	0x0000 00 00 06 2a 5b 5d 69 6e 74                       ...*[]int
type.*[]int SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 1b 31 52 88 08 08 08 36 00 00 00 00 00 00 00 00  .1R....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]int-+0
	rel 48+8 t=1 type.[]int+0
type.[]int SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 8e 66 f9 1b 02 08 08 17 00 00 00 00 00 00 00 00  .f..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]int-+0
	rel 44+4 t=6 type.*[]int+0
	rel 48+8 t=1 type.int+0
type..eqfunc48 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 30 00 00 00 00 00 00 00  ........0.......
	rel 0+8 t=1 runtime.memequal_varlen+0
type..namedata.*[6]int- SRODATA dupok size=10
	0x0000 00 00 07 2a 5b 36 5d 69 6e 74                    ...*[6]int
type.*[6]int SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 6f bf f5 08 08 08 36 00 00 00 00 00 00 00 00  Oo.....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[6]int-+0
	rel 48+8 t=1 type.[6]int+0
runtime.gcbits. SRODATA dupok size=0
type.[6]int SRODATA dupok size=72
	0x0000 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  0...............
	0x0010 26 6a 03 b7 0a 08 08 11 00 00 00 00 00 00 00 00  &j..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 06 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 type..eqfunc48+0
	rel 32+8 t=1 runtime.gcbits.+0
	rel 40+4 t=5 type..namedata.*[6]int-+0
	rel 44+4 t=6 type.*[6]int+0
	rel 48+8 t=1 type.int+0
	rel 56+8 t=1 type.[]int+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*os.File,io.Writer+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·9fb7f0986f647f17cb53dda1484e0f7a SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 00 01                    ..........
gclocals·1a65e721a2ccc325b382662e7ffee780 SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 01 00                    ..........
gclocals·d571c0f6cf0af59df28f76498f639cf2 SRODATA dupok size=10
	0x0000 02 00 00 00 04 00 00 00 00 08                    ..........
gclocals·568470801006e5c0dc3947ea998fe279 SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 00 02                    ..........
gclocals·ba192201ac73f95fb90b551d9176d705 SRODATA dupok size=12
	0x0000 04 00 00 00 02 00 00 00 00 01 02 03              ............
"".main.stkobj SRODATA size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
